version: '3.8'

services:
  postgres:
    image: ankane/pgvector:latest
    container_name: ragchatbot-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ragchatbot
    ports:
      - "5432:5432"
    volumes:
      - postgres_ragchatbot_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

volumes:
  postgres_ragchatbot_data: 